services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Tokyo
      - DATABASE_URL=sqlite:///./data/app.db
      - ENVIRONMENT=production
      - BASE_URL=https://url-click-manager.xvps.jp
      - SECRET_KEY=url-shortener-production-secret-key-2024
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Tokyo
      - NEXT_PUBLIC_API_URL=https://url-click-manager.xvps.jp
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data: 