services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3001:3000"
    environment:
      - TZ=Asia/Tokyo
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    restart: unless-stopped 